// IWYU pragma: no_include <bits/std_abs.h>
#include "credits.h"

#include <SDL3/SDL.h>  // Para SDL_RenderFillRect, SDL_RenderTexture, SDL_SetRenderTarget, SDL_SetRenderDrawColor, SDL_CreateTexture, SDL_DestroyTexture, SDL_GetTicks, SDL_GetRenderTarget, SDL_PixelFormat, SDL_PollEvent, SDL_RenderClear, SDL_RenderRect, SDL_SetTextureBlendMode, SDL_TextureAccess, SDL_BLENDMODE_BLEND, SDL_Event

#include <algorithm>    // Para max, min, clamp
#include <array>        // Para array
#include <stdexcept>    // Para runtime_error
#include <string>       // Para basic_string, string
#include <string_view>  // Para string_view
#include <vector>       // Para vector

#include "audio.h"            // Para Audio
#include "balloon_manager.h"  // Para BalloonManager
#include "color.h"            // Para Zone, SHADOW_TEXT_COLOR, NO_TEXT_COLOR, Color
#include "fade.h"             // Para Fade, FadeType, FadeMode
#include "global_events.h"    // Para check
#include "global_inputs.h"    // Para check
#include "input.h"            // Para Input, Input::ALLOW_REPEAT
#include "lang.h"             // Para getText
#include "param.h"            // Para Param, param, ParamGame, ParamFade
#include "player.h"           // Para Player, PlayerState
#include "resource.h"         // Para Resource
#include "screen.h"           // Para Screen
#include "section.hpp"        // Para Name, name
#include "sprite.h"           // Para Sprite
#include "text.h"             // Para Text, TEXT_CENTER, TEXT_SHADOW
#include "texture.h"          // Para Texture
#include "tiled_bg.h"         // Para TiledBG, TiledBGMode
#include "ui/service_menu.h"  // Para ServiceMenu
#include "utils.h"

// Textos
constexpr std::string_view TEXT_COPYRIGHT = "@2020,2025 JailDesigner";

// Constructor
Credits::Credits()
    : balloon_manager_(std::make_unique<BalloonManager>()),
      tiled_bg_(std::make_unique<TiledBG>(param.game.game_area.rect, TiledBGMode::DIAGONAL)),
      fade_in_(std::make_unique<Fade>()),
      fade_out_(std::make_unique<Fade>()),
      text_texture_(SDL_CreateTexture(Screen::get()->getRenderer(), SDL_PIXELFORMAT_RGBA8888, SDL_TEXTUREACCESS_TARGET, param.game.width, param.game.height)),
      canvas_(SDL_CreateTexture(Screen::get()->getRenderer(), SDL_PIXELFORMAT_RGBA8888, SDL_TEXTUREACCESS_TARGET, param.game.width, param.game.height)) {
    if (text_texture_ == nullptr) {
        throw std::runtime_error("Failed to create SDL texture for text.");
    }
    Section::name = Section::Name::CREDITS;
    balloon_manager_->setPlayArea(play_area_);

    fade_in_->setColor(param.fade.color);
    fade_in_->setType(FadeType::FULLSCREEN);
    fade_in_->setPostDuration(50);
    fade_in_->setMode(FadeMode::IN);
    fade_in_->activate();

    fade_out_->setColor(0, 0, 0);
    fade_out_->setType(FadeType::FULLSCREEN);
    fade_out_->setPostDuration(400);

    updateRedRect();
    tiled_bg_->setColor(Color(255, 96, 96));

    initPlayers();
    SDL_SetTextureBlendMode(text_texture_, SDL_BLENDMODE_BLEND);
    fillTextTexture();
    steps_ = std::abs((top_black_rect_.h - param.game.game_area.center_y - 1) + ((left_black_rect_.w - param.game.game_area.center_x) / 4));
}

// Destructor
Credits::~Credits() {
    SDL_DestroyTexture(text_texture_);
    SDL_DestroyTexture(canvas_);
    resetVolume();
    Audio::get()->stopMusic();
}

// Bucle principal
void Credits::run() {
    while (Section::name == Section::Name::CREDITS) {
        checkInput();
        update();
        checkEvents();  // Tiene que ir antes del render
        render();
    }
}

// Actualiza las variables
void Credits::update() {
    if (SDL_GetTicks() - ticks_ > param.game.speed) {
        ticks_ = SDL_GetTicks();
        const int REPEAT = want_to_pass_ ? 4 : 1;
        for (int i = 0; i < REPEAT; ++i) {
            tiled_bg_->update();
            cycleColors();
            balloon_manager_->update();
            updateTextureDstRects();
            throwBalloons();
            updatePlayers();
            updateAllFades();
            ++counter_;
        }

        Screen::get()->update();

        fillCanvas();
    }
    static const auto audio = Audio::get();
    audio->update();
}

// Dibuja Credits::en patalla
void Credits::render() {
    static const auto screen = Screen::get();

    screen->start();                                                      // Prepara para empezar a dibujar en la textura de juego
    SDL_RenderTexture(screen->getRenderer(), canvas_, nullptr, nullptr);  // Copia la textura con la zona de juego a la pantalla
    screen->render();                                                     // Vuelca el contenido del renderizador en pantalla
}

// Comprueba el manejador de eventos
void Credits::checkEvents() {
    SDL_Event event;
    while (SDL_PollEvent(&event)) {
        GlobalEvents::check(event);
    }
}

// Comprueba las entradas
void Credits::checkInput() {
    Input::get()->update();

    if (!ServiceMenu::get()->isEnabled()) {
        // Comprueba si se ha pulsado cualquier botón (de los usados para jugar)
        if (Input::get()->checkAnyButton(Input::ALLOW_REPEAT)) {
            want_to_pass_ = true;
            fading_ = mini_logo_on_position_;
        } else {
            want_to_pass_ = false;
        }
    }

    // Comprueba los inputs que se pueden introducir en cualquier sección del juego
    GlobalInputs::check();
}

// Crea la textura con el texto
void Credits::fillTextTexture() {
    auto text = Resource::get()->getText("smb2");
    auto text_grad = Resource::get()->getText("smb2_grad");
    SDL_SetRenderTarget(Screen::get()->getRenderer(), text_texture_);

    SDL_SetRenderDrawColor(Screen::get()->getRenderer(), 0, 0, 0, 0);
    SDL_RenderClear(Screen::get()->getRenderer());

    const std::array<std::string, 11> TEXTS = {
        Lang::getText("[CREDITS] PROGRAMMED_AND_DESIGNED_BY"),
        Lang::getText("[CREDITS] PIXELART_DRAWN_BY"),
        Lang::getText("[CREDITS] MUSIC_COMPOSED_BY"),
        Lang::getText("[CREDITS] SOUND_EFFECTS"),
        "JAILDESIGNER",
        "JAILDOCTOR",
        "ERIC MATYAS (SOUNDIMAGE.ORG)",
        "WWW.THEMOTIONMONKEY.CO.UK",
        "WWW.KENNEY.NL",
        "JAILDOCTOR",
        "JAILDESIGNER"};

    const int SPACE_POST_TITLE = 3 + text->getCharacterSize();
    const int SPACE_PRE_TITLE = text->getCharacterSize() * 4;
    const int TEXTS_HEIGHT = 1 * text->getCharacterSize() + 8 * SPACE_POST_TITLE + 3 * SPACE_PRE_TITLE;
    credits_rect_dst_.h = credits_rect_src_.h = TEXTS_HEIGHT;

    // PROGRAMMED_AND_DESIGNED_BY
    int y = 0;
    text_grad->writeDX(TEXT_CENTER | TEXT_SHADOW, param.game.game_area.center_x, y, TEXTS.at(0), 1, NO_TEXT_COLOR, 1, SHADOW_TEXT_COLOR);

    y += SPACE_POST_TITLE;
    text->writeDX(TEXT_CENTER | TEXT_SHADOW, param.game.game_area.center_x, y, TEXTS.at(4), 1, NO_TEXT_COLOR, 1, SHADOW_TEXT_COLOR);

    // PIXELART_DRAWN_BY
    y += SPACE_PRE_TITLE;
    text_grad->writeDX(TEXT_CENTER | TEXT_SHADOW, param.game.game_area.center_x, y, TEXTS.at(1), 1, NO_TEXT_COLOR, 1, SHADOW_TEXT_COLOR);
    y += SPACE_POST_TITLE;
    text->writeDX(TEXT_CENTER | TEXT_SHADOW, param.game.game_area.center_x, y, TEXTS.at(4), 1, NO_TEXT_COLOR, 1, SHADOW_TEXT_COLOR);

    // MUSIC_COMPOSED_BY
    y += SPACE_PRE_TITLE;
    text_grad->writeDX(TEXT_CENTER | TEXT_SHADOW, param.game.game_area.center_x, y, TEXTS.at(2), 1, NO_TEXT_COLOR, 1, SHADOW_TEXT_COLOR);

    y += SPACE_POST_TITLE;
    text->writeDX(TEXT_CENTER | TEXT_SHADOW, param.game.game_area.center_x, y, TEXTS.at(5), 1, NO_TEXT_COLOR, 1, SHADOW_TEXT_COLOR);
    y += SPACE_POST_TITLE;
    text->writeDX(TEXT_CENTER | TEXT_SHADOW, param.game.game_area.center_x, y, TEXTS.at(6), 1, NO_TEXT_COLOR, 1, SHADOW_TEXT_COLOR);

    // SOUND_EFFECTS
    y += SPACE_PRE_TITLE;
    text_grad->writeDX(TEXT_CENTER | TEXT_SHADOW, param.game.game_area.center_x, y, TEXTS.at(3), 1, NO_TEXT_COLOR, 1, SHADOW_TEXT_COLOR);
    y += SPACE_POST_TITLE;
    text->writeDX(TEXT_CENTER | TEXT_SHADOW, param.game.game_area.center_x, y, TEXTS.at(7), 1, NO_TEXT_COLOR, 1, SHADOW_TEXT_COLOR);
    y += SPACE_POST_TITLE;
    text->writeDX(TEXT_CENTER | TEXT_SHADOW, param.game.game_area.center_x, y, TEXTS.at(8), 1, NO_TEXT_COLOR, 1, SHADOW_TEXT_COLOR);
    y += SPACE_POST_TITLE;
    text->writeDX(TEXT_CENTER | TEXT_SHADOW, param.game.game_area.center_x, y, TEXTS.at(9), 1, NO_TEXT_COLOR, 1, SHADOW_TEXT_COLOR);
    y += SPACE_POST_TITLE;
    text->writeDX(TEXT_CENTER | TEXT_SHADOW, param.game.game_area.center_x, y, TEXTS.at(10), 1, NO_TEXT_COLOR, 1, SHADOW_TEXT_COLOR);

    // Mini logo
    y += SPACE_PRE_TITLE;
    mini_logo_rect_src_.y = y;
    auto mini_logo_sprite = std::make_unique<Sprite>(Resource::get()->getTexture("logo_jailgames_mini.png"));
    mini_logo_sprite->setPosition(1 + param.game.game_area.center_x - mini_logo_sprite->getWidth() / 2, 1 + y);
    Resource::get()->getTexture("logo_jailgames_mini.png")->setColor(SHADOW_TEXT_COLOR.r, SHADOW_TEXT_COLOR.g, SHADOW_TEXT_COLOR.b);
    mini_logo_sprite->render();

    mini_logo_sprite->setPosition(param.game.game_area.center_x - mini_logo_sprite->getWidth() / 2, y);
    Resource::get()->getTexture("logo_jailgames_mini.png")->setColor(255, 255, 255);
    mini_logo_sprite->render();

    // Texto con el copyright
    y += mini_logo_sprite->getHeight() + 3;
    text->writeDX(TEXT_CENTER | TEXT_SHADOW, param.game.game_area.center_x, y, std::string(TEXT_COPYRIGHT), 1, NO_TEXT_COLOR, 1, SHADOW_TEXT_COLOR);

    // Resetea el renderizador
    SDL_SetRenderTarget(Screen::get()->getRenderer(), nullptr);

    // Actualiza las variables
    mini_logo_rect_dst_.h = mini_logo_rect_src_.h = mini_logo_sprite->getHeight() + 3 + text->getCharacterSize();
    credits_rect_dst_.y = param.game.game_area.rect.h;
    mini_logo_rect_dst_.y = credits_rect_dst_.y + credits_rect_dst_.h + 30;
    mini_logo_final_pos_ = param.game.game_area.center_y - mini_logo_rect_src_.h / 2;
}

// Dibuja todos los sprites en la textura
void Credits::fillCanvas() {
    // Cambia el destino del renderizador
    auto *temp = SDL_GetRenderTarget(Screen::get()->getRenderer());
    SDL_SetRenderTarget(Screen::get()->getRenderer(), canvas_);

    // Dibuja el fondo, los globos y los jugadores
    tiled_bg_->render();
    balloon_manager_->render();
    renderPlayers();

    // Dibuja los titulos de credito
    SDL_RenderTexture(Screen::get()->getRenderer(), text_texture_, &credits_rect_src_, &credits_rect_dst_);

    // Dibuja el mini_logo
    SDL_RenderTexture(Screen::get()->getRenderer(), text_texture_, &mini_logo_rect_src_, &mini_logo_rect_dst_);

    // Dibuja los rectangulos negros
    SDL_SetRenderDrawColor(Screen::get()->getRenderer(), 0, 0, 0, 0xFF);
    SDL_RenderFillRect(Screen::get()->getRenderer(), &top_black_rect_);
    SDL_RenderFillRect(Screen::get()->getRenderer(), &bottom_black_rect_);
    SDL_RenderFillRect(Screen::get()->getRenderer(), &left_black_rect_);
    SDL_RenderFillRect(Screen::get()->getRenderer(), &right_black_rect_);

    // Dibuja el rectangulo rojo
    // SDL_SetRenderDrawColor(Screen::get()->getRenderer(), 0xFF, 0, 0, 0xFF);
    const Color COLOR = color_.LIGHTEN();
    SDL_SetRenderDrawColor(Screen::get()->getRenderer(), COLOR.r, COLOR.g, COLOR.b, 0xFF);
    SDL_RenderRect(Screen::get()->getRenderer(), &border_rect_);

    // Si el mini_logo está en su destino, lo dibuja encima de lo anterior
    if (mini_logo_on_position_) {
        SDL_RenderTexture(Screen::get()->getRenderer(), text_texture_, &mini_logo_rect_src_, &mini_logo_rect_dst_);
    }

    // Dibuja el fade sobre el resto de elementos
    fade_in_->render();
    fade_out_->render();

    // Deja el renderizador apuntando donde estaba
    SDL_SetRenderTarget(Screen::get()->getRenderer(), temp);
}

// Actualiza el destino de los rectangulos de las texturas
void Credits::updateTextureDstRects() {
    if (counter_ % 10 == 0) {
        // Comprueba la posición de la textura con los titulos de credito
        if (credits_rect_dst_.y + credits_rect_dst_.h > play_area_.y) {
            --credits_rect_dst_.y;
        }

        // Comprueba la posición de la textura con el mini_logo
        if (mini_logo_rect_dst_.y == mini_logo_final_pos_) {
            mini_logo_on_position_ = true;

            // Si el jugador quiere pasar los titulos de credito, el fade se inicia solo
            if (want_to_pass_) {
                fading_ = true;
            }

            // Se activa el contador para evitar que la sección sea infinita
            if (counter_prevent_endless_ == 1000) {
                fading_ = true;
            } else {
                ++counter_prevent_endless_;
            }
        } else {
            --mini_logo_rect_dst_.y;
        }
    }
}

// Tira globos al escenario
void Credits::throwBalloons() {
    constexpr int SPEED = 200;
    const std::vector<int> SETS = {0, 63, 25, 67, 17, 75, 13, 50};

    if (counter_ > ((SETS.size() - 1) * SPEED) * 3) {
        return;
    }

    if (counter_ % SPEED == 0) {
        const int INDEX = (counter_ / SPEED) % SETS.size();
        balloon_manager_->deployFormation(SETS.at(INDEX), -60);
    }

    if (counter_ % (SPEED * 4) == 0 && counter_ > 0) {
        balloon_manager_->createPowerBall();
    }
}

// Inicializa los jugadores
void Credits::initPlayers() {
    std::vector<std::vector<std::shared_ptr<Texture>>> player_textures;  // Vector con todas las texturas de los jugadores;
    std::vector<std::vector<std::string>> player_animations;             // Vector con las animaciones del jugador

    // Texturas - Player1
    {
        std::vector<std::shared_ptr<Texture>> player_texture;
        player_texture.emplace_back(Resource::get()->getTexture("player1.gif"));
        player_texture.emplace_back(Resource::get()->getTexture("player1_power.png"));
        player_textures.push_back(player_texture);
    }

    // Texturas - Player2
    {
        std::vector<std::shared_ptr<Texture>> player_texture;
        player_texture.emplace_back(Resource::get()->getTexture("player2.gif"));
        player_texture.emplace_back(Resource::get()->getTexture("player2_power.png"));
        player_textures.push_back(player_texture);
    }

    // Animaciones -- Jugador
    {
        player_animations.emplace_back(Resource::get()->getAnimation("player.ani"));
        player_animations.emplace_back(Resource::get()->getAnimation("player_power.ani"));
    }

    // Crea los dos jugadores
    constexpr int PLAYER_WIDTH = 32;
    const int Y = play_area_.y + play_area_.h - PLAYER_WIDTH;
    constexpr bool DEMO = false;
    constexpr int AWAY_DISTANCE = 700;
    players_.emplace_back(std::make_unique<Player>(1, play_area_.x - AWAY_DISTANCE - PLAYER_WIDTH, Y, DEMO, play_area_, player_textures.at(0), player_animations));
    players_.back()->setWalkingState(Player::State::WALKING_RIGHT);
    players_.back()->setPlayingState(Player::State::CREDITS);

    players_.emplace_back(std::make_unique<Player>(2, play_area_.x + play_area_.w + AWAY_DISTANCE, Y, DEMO, play_area_, player_textures.at(1), player_animations));
    players_.back()->setWalkingState(Player::State::WALKING_LEFT);
    players_.back()->setPlayingState(Player::State::CREDITS);
}

// Actualiza los rectangulos negros
void Credits::updateBlackRects() {
    static int current_step_ = steps_;
    if (top_black_rect_.h != param.game.game_area.center_y - 1 && bottom_black_rect_.y != param.game.game_area.center_y + 1) {
        // Si los rectangulos superior e inferior no han llegado al centro
        if (counter_ % 4 == 0) {
            // Incrementa la altura del rectangulo superior
            top_black_rect_.h = std::min(top_black_rect_.h + 1, param.game.game_area.center_y - 1);

            // Incrementa la altura y modifica la posición del rectangulo inferior
            ++bottom_black_rect_.h;
            bottom_black_rect_.y = std::max(bottom_black_rect_.y - 1, param.game.game_area.center_y + 1);

            --current_step_;
            setVolume((initial_volume_ * current_step_ / steps_));
        }
    } else {
        // Si los rectangulos superior e inferior han llegado al centro
        if (left_black_rect_.w != param.game.game_area.center_x && right_black_rect_.x != param.game.game_area.center_x) {
            constexpr int SPEED = 2;
            // Si los rectangulos izquierdo y derecho no han llegado al centro
            // Incrementa la anchura del rectangulo situado a la izquierda
            left_black_rect_.w = std::min(left_black_rect_.w + SPEED, param.game.game_area.center_x);

            // Incrementa la anchura y modifica la posición del rectangulo situado a la derecha
            right_black_rect_.w += SPEED;
            right_black_rect_.x = std::max(right_black_rect_.x - SPEED, param.game.game_area.center_x);

            --current_step_;
            setVolume((initial_volume_ * current_step_ / steps_));
        } else {
            // Si los rectangulos izquierdo y derecho han llegado al centro
            setVolume(0);
            Audio::get()->stopMusic();
            if (counter_pre_fade_ == 400) {
                fade_out_->activate();
            } else {
                ++counter_pre_fade_;
            }
        }
    }
}

// Actualiza el rectangulo rojo
void Credits::updateRedRect() {
    border_rect_.x = left_black_rect_.x + left_black_rect_.w;
    border_rect_.y = top_black_rect_.y + top_black_rect_.h - 1;
    border_rect_.w = right_black_rect_.x - border_rect_.x;
    border_rect_.h = bottom_black_rect_.y - border_rect_.y + 1;
}

// Actualiza el estado de fade
void Credits::updateAllFades() {
    if (fading_) {
        updateBlackRects();
        updateRedRect();
    }

    fade_in_->update();
    if (fade_in_->hasEnded()) {
        Audio::get()->playMusic("credits.ogg");
    }

    fade_out_->update();
    if (fade_out_->hasEnded()) {
        Section::name = Section::Name::HI_SCORE_TABLE;
    }
}

// Establece el nivel de volumen
void Credits::setVolume(int amount) {
    Options::audio.music.volume = std::clamp(amount, 0, 100);
    Audio::get()->setMusicVolume(Options::audio.music.volume);
}

// Reestablece el nivel de volumen
void Credits::resetVolume() const {
    Options::audio.music.volume = initial_volume_;
    Audio::get()->setMusicVolume(Options::audio.music.volume);
}

// Cambia el color del fondo
void Credits::cycleColors() {
    // constexpr int UPPER_LIMIT = 255; // Límite superior
    // constexpr int LOWER_LIMIT = 80;  // Límite inferior

    constexpr int UPPER_LIMIT = 140;  // Límite superior
    constexpr int LOWER_LIMIT = 30;   // Límite inferior

    static auto r_ = static_cast<float>(UPPER_LIMIT);
    static auto g_ = static_cast<float>(LOWER_LIMIT);
    static auto b_ = static_cast<float>(LOWER_LIMIT);
    static float step_r_ = -0.5F;  // Paso flotante para transiciones suaves
    static float step_g_ = 0.3F;
    static float step_b_ = 0.1F;

    // Ajustar valores de R
    r_ += step_r_;
    if (r_ >= UPPER_LIMIT || r_ <= LOWER_LIMIT) {
        step_r_ = -step_r_;  // Cambia de dirección al alcanzar los límites
    }

    // Ajustar valores de G
    g_ += step_g_;
    if (g_ >= UPPER_LIMIT || g_ <= LOWER_LIMIT) {
        step_g_ = -step_g_;  // Cambia de dirección al alcanzar los límites
    }

    // Ajustar valores de B
    b_ += step_b_;
    if (b_ >= UPPER_LIMIT || b_ <= LOWER_LIMIT) {
        step_b_ = -step_b_;  // Cambia de dirección al alcanzar los límites
    }

    // Aplicar el color, redondeando a enteros antes de usar
    color_ = Color(static_cast<int>(r_), static_cast<int>(g_), static_cast<int>(b_));
    tiled_bg_->setColor(color_);
}

// Actualza los jugadores
void Credits::updatePlayers() {
    for (auto &player : players_) {
        player->update();
    }
}

// Renderiza los jugadores
void Credits::renderPlayers() {
    for (auto const &player : players_) {
        player->render();
    }
}
