#pragma once

// --- Includes ---
#include <SDL3/SDL.h>
#include <stdint.h>  // Para uint32_t, uint8_t
#include <stdio.h>   // Para NULL, fseek, fclose, fopen, fread, ftell, FILE, SEEK_END, SEEK_SET
#include <stdlib.h>  // Para free, malloc

#include <iostream>  // Para std::cout
#include <memory>    // Para std::unique_ptr
#include <string>    // Para std::string
#include <vector>    // Para std::vector

#define STB_VORBIS_HEADER_ONLY
#include "external/stb_vorbis.c"  // Para stb_vorbis_open_memory i streaming

// Deleter stateless per a buffers reservats amb `SDL_malloc` / `SDL_LoadWAV*`.
// Compatible amb `std::unique_ptr<Uint8[], SDLFreeDeleter>` — zero size
// overhead gràcies a EBO, igual que un unique_ptr amb default_delete.
struct SDLFreeDeleter {
    void operator()(Uint8* p) const noexcept {
        if (p) SDL_free(p);
    }
};

// --- Public Enums ---
enum JA_Channel_state {
    JA_CHANNEL_INVALID,
    JA_CHANNEL_FREE,
    JA_CHANNEL_PLAYING,
    JA_CHANNEL_PAUSED,
    JA_SOUND_DISABLED,
};
enum JA_Music_state {
    JA_MUSIC_INVALID,
    JA_MUSIC_PLAYING,
    JA_MUSIC_PAUSED,
    JA_MUSIC_STOPPED,
    JA_MUSIC_DISABLED,
};

// --- Struct Definitions ---
#define JA_MAX_SIMULTANEOUS_CHANNELS 20
#define JA_MAX_GROUPS 2

struct JA_Sound_t {
    SDL_AudioSpec spec{SDL_AUDIO_S16, 2, 48000};
    Uint32 length{0};
    // Buffer descomprimit (PCM) propietat del sound. Reservat per SDL_LoadWAV
    // via SDL_malloc; el deleter `SDLFreeDeleter` allibera amb SDL_free.
    std::unique_ptr<Uint8[], SDLFreeDeleter> buffer;
};

struct JA_Channel_t {
    JA_Sound_t* sound{nullptr};
    int pos{0};
    int times{0};
    int group{0};
    SDL_AudioStream* stream{nullptr};
    JA_Channel_state state{JA_CHANNEL_FREE};
};

struct JA_Music_t {
    SDL_AudioSpec spec{SDL_AUDIO_S16, 2, 48000};

    // OGG comprimit en memòria. Propietat nostra; es copia des del buffer
    // d'entrada una sola vegada en JA_LoadMusic i es descomprimix en chunks
    // per streaming. Com que stb_vorbis guarda un punter persistent al
    // `.data()` d'aquest vector, no el podem resize'jar un cop establert
    // (una reallocation invalidaria el punter que el decoder conserva).
    std::vector<Uint8> ogg_data;
    stb_vorbis* vorbis{nullptr};  // handle del decoder, viu tot el cicle del JA_Music_t

    std::string filename;

    int times{0};  // loops restants (-1 = infinit, 0 = un sol play)
    SDL_AudioStream* stream{nullptr};
    JA_Music_state state{JA_MUSIC_INVALID};
};

// --- Internal Global State (inline, C++17) ---

inline JA_Music_t* current_music{nullptr};
inline JA_Channel_t channels[JA_MAX_SIMULTANEOUS_CHANNELS];

inline SDL_AudioSpec JA_audioSpec{SDL_AUDIO_S16, 2, 48000};
inline float JA_musicVolume{1.0f};
inline float JA_soundVolume[JA_MAX_GROUPS];
inline bool JA_musicEnabled{true};
inline bool JA_soundEnabled{true};
inline SDL_AudioDeviceID sdlAudioDevice{0};

// --- Crossfade / Fade State ---
struct JA_FadeState {
    bool active{false};
    Uint64 start_time{0};
    int duration_ms{0};
    float initial_volume{0.0f};
};

struct JA_OutgoingMusic {
    SDL_AudioStream* stream{nullptr};
    JA_FadeState fade;
};

inline JA_OutgoingMusic outgoing_music;
inline JA_FadeState incoming_fade;

// --- Forward Declarations ---
inline void JA_StopMusic();
inline void JA_StopChannel(const int channel);
inline int JA_PlaySoundOnChannel(JA_Sound_t* sound, const int channel, const int loop = 0, const int group = 0);
inline void JA_CrossfadeMusic(JA_Music_t* music, int crossfade_ms, int loop = -1);

// --- Music streaming internals ---
// Bytes-per-sample per canal (sempre s16)
static constexpr int JA_MUSIC_BYTES_PER_SAMPLE = 2;
// Quants shorts decodifiquem per crida a get_samples_short_interleaved.
// 8192 shorts = 4096 samples/channel en estèreo ≈ 85ms de so a 48kHz.
static constexpr int JA_MUSIC_CHUNK_SHORTS = 8192;
// Umbral d'audio per davant del cursor de reproducció. Mantenim ≥ 0.5 s a
// l'SDL_AudioStream per absorbir jitter de frame i evitar underruns.
static constexpr float JA_MUSIC_LOW_WATER_SECONDS = 0.5f;

// Decodifica un chunk del vorbis i el volca a l'stream. Retorna samples
// decodificats per canal (0 = EOF de l'stream vorbis).
inline int JA_FeedMusicChunk(JA_Music_t* music) {
    if (!music || !music->vorbis || !music->stream) return 0;

    short chunk[JA_MUSIC_CHUNK_SHORTS];
    const int num_channels = music->spec.channels;
    const int samples_per_channel = stb_vorbis_get_samples_short_interleaved(
        music->vorbis,
        num_channels,
        chunk,
        JA_MUSIC_CHUNK_SHORTS);
    if (samples_per_channel <= 0) return 0;

    const int bytes = samples_per_channel * num_channels * JA_MUSIC_BYTES_PER_SAMPLE;
    SDL_PutAudioStreamData(music->stream, chunk, bytes);
    return samples_per_channel;
}

// Reompli l'stream fins que tinga ≥ JA_MUSIC_LOW_WATER_SECONDS bufferats.
// En arribar a EOF del vorbis, aplica el loop (times) o deixa drenar.
inline void JA_PumpMusic(JA_Music_t* music) {
    if (!music || !music->vorbis || !music->stream) return;

    const int bytes_per_second = music->spec.freq * music->spec.channels * JA_MUSIC_BYTES_PER_SAMPLE;
    const int low_water_bytes = static_cast<int>(JA_MUSIC_LOW_WATER_SECONDS * static_cast<float>(bytes_per_second));

    while (SDL_GetAudioStreamAvailable(music->stream) < low_water_bytes) {
        const int decoded = JA_FeedMusicChunk(music);
        if (decoded > 0) continue;

        // EOF: si queden loops, rebobinar; si no, tallar i deixar drenar.
        if (music->times != 0) {
            stb_vorbis_seek_start(music->vorbis);
            if (music->times > 0) music->times--;
        } else {
            break;
        }
    }
}

// Pre-carrega `duration_ms` de so dins l'stream actual abans que l'stream
// siga robat per outgoing_music (crossfade o fade-out). Imprescindible amb
// streaming: l'stream robat no es pot re-alimentar perquè perd la referència
// al seu vorbis decoder. No aplica loop — si el vorbis s'esgota abans, parem.
inline void JA_PreFillOutgoing(JA_Music_t* music, int duration_ms) {
    if (!music || !music->vorbis || !music->stream) return;

    const int bytes_per_second = music->spec.freq * music->spec.channels * JA_MUSIC_BYTES_PER_SAMPLE;
    const int needed_bytes = static_cast<int>((static_cast<int64_t>(duration_ms) * bytes_per_second) / 1000);

    while (SDL_GetAudioStreamAvailable(music->stream) < needed_bytes) {
        const int decoded = JA_FeedMusicChunk(music);
        if (decoded <= 0) break;  // EOF: deixem drenar el que hi haja
    }
}

// --- Core Functions ---

inline void JA_Update() {
    // --- Outgoing music fade-out (crossfade o fade-out a silencio) ---
    if (outgoing_music.stream && outgoing_music.fade.active) {
        Uint64 now = SDL_GetTicks();
        Uint64 elapsed = now - outgoing_music.fade.start_time;
        if (elapsed >= (Uint64)outgoing_music.fade.duration_ms) {
            SDL_DestroyAudioStream(outgoing_music.stream);
            outgoing_music.stream = nullptr;
            outgoing_music.fade.active = false;
        } else {
            float percent = (float)elapsed / (float)outgoing_music.fade.duration_ms;
            SDL_SetAudioStreamGain(outgoing_music.stream, outgoing_music.fade.initial_volume * (1.0f - percent));
        }
    }

    // --- Current music ---
    if (JA_musicEnabled && current_music && current_music->state == JA_MUSIC_PLAYING) {
        // Fade-in (parte de un crossfade)
        if (incoming_fade.active) {
            Uint64 now = SDL_GetTicks();
            Uint64 elapsed = now - incoming_fade.start_time;
            if (elapsed >= (Uint64)incoming_fade.duration_ms) {
                incoming_fade.active = false;
                SDL_SetAudioStreamGain(current_music->stream, JA_musicVolume);
            } else {
                float percent = (float)elapsed / (float)incoming_fade.duration_ms;
                SDL_SetAudioStreamGain(current_music->stream, JA_musicVolume * percent);
            }
        }

        // Streaming: rellenem l'stream fins al low-water-mark i parem si el
        // vorbis s'ha esgotat i no queden loops.
        JA_PumpMusic(current_music);
        if (current_music->times == 0 && SDL_GetAudioStreamAvailable(current_music->stream) == 0) {
            JA_StopMusic();
        }
    }

    // --- Sound channels ---
    if (JA_soundEnabled) {
        for (int i = 0; i < JA_MAX_SIMULTANEOUS_CHANNELS; ++i)
            if (channels[i].state == JA_CHANNEL_PLAYING) {
                if (channels[i].times != 0) {
                    if ((Uint32)SDL_GetAudioStreamAvailable(channels[i].stream) < (channels[i].sound->length / 2)) {
                        SDL_PutAudioStreamData(channels[i].stream, channels[i].sound->buffer.get(), channels[i].sound->length);
                        if (channels[i].times > 0) channels[i].times--;
                    }
                } else {
                    if (SDL_GetAudioStreamAvailable(channels[i].stream) == 0) JA_StopChannel(i);
                }
            }
    }
}

inline void JA_Init(const int freq, const SDL_AudioFormat format, const int num_channels) {
    JA_audioSpec = {format, num_channels, freq};
    if (sdlAudioDevice) SDL_CloseAudioDevice(sdlAudioDevice);
    sdlAudioDevice = SDL_OpenAudioDevice(SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK, &JA_audioSpec);
    if (sdlAudioDevice == 0) std::cout << "Failed to initialize SDL audio!" << '\n';
    for (int i = 0; i < JA_MAX_SIMULTANEOUS_CHANNELS; ++i) channels[i].state = JA_CHANNEL_FREE;
    for (int i = 0; i < JA_MAX_GROUPS; ++i) JA_soundVolume[i] = 0.5f;
}

inline void JA_Quit() {
    if (outgoing_music.stream) {
        SDL_DestroyAudioStream(outgoing_music.stream);
        outgoing_music.stream = nullptr;
    }
    if (sdlAudioDevice) SDL_CloseAudioDevice(sdlAudioDevice);
    sdlAudioDevice = 0;
}

// --- Music Functions ---

inline JA_Music_t* JA_LoadMusic(const Uint8* buffer, Uint32 length) {
    if (!buffer || length == 0) return nullptr;

    // Allocem el JA_Music_t primer per aprofitar el seu `std::vector<Uint8>`
    // com a propietari del OGG comprimit. stb_vorbis guarda un punter
    // persistent al buffer; com que ací no el resize'jem, el .data() és
    // estable durant tot el cicle de vida del music.
    auto* music = new JA_Music_t();
    music->ogg_data.assign(buffer, buffer + length);

    int error = 0;
    music->vorbis = stb_vorbis_open_memory(music->ogg_data.data(),
        static_cast<int>(length),
        &error,
        nullptr);
    if (!music->vorbis) {
        std::cout << "JA_LoadMusic: stb_vorbis_open_memory failed (error " << error << ")" << '\n';
        delete music;
        return nullptr;
    }

    const stb_vorbis_info info = stb_vorbis_get_info(music->vorbis);
    music->spec.channels = info.channels;
    music->spec.freq = static_cast<int>(info.sample_rate);
    music->spec.format = SDL_AUDIO_S16;
    music->state = JA_MUSIC_STOPPED;

    return music;
}

// Overload amb filename — els callers l'usen per poder comparar la música
// en curs amb JA_GetMusicFilename() i no rearrancar-la si ja és la mateixa.
inline JA_Music_t* JA_LoadMusic(Uint8* buffer, Uint32 length, const char* filename) {
    JA_Music_t* music = JA_LoadMusic(static_cast<const Uint8*>(buffer), length);
    if (music && filename) music->filename = filename;
    return music;
}

inline JA_Music_t* JA_LoadMusic(const char* filename) {
    // Carreguem primer el arxiu en memòria i després el descomprimim.
    FILE* f = fopen(filename, "rb");
    if (!f) return nullptr;
    fseek(f, 0, SEEK_END);
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET);
    auto* buffer = static_cast<Uint8*>(malloc(fsize + 1));
    if (!buffer) {
        fclose(f);
        return nullptr;
    }
    if (fread(buffer, fsize, 1, f) != 1) {
        fclose(f);
        free(buffer);
        return nullptr;
    }
    fclose(f);

    JA_Music_t* music = JA_LoadMusic(static_cast<const Uint8*>(buffer), static_cast<Uint32>(fsize));
    if (music) {
        music->filename = filename;
    }

    free(buffer);

    return music;
}

inline void JA_PlayMusic(JA_Music_t* music, const int loop = -1) {
    if (!JA_musicEnabled || !music || !music->vorbis) return;

    JA_StopMusic();

    current_music = music;
    current_music->state = JA_MUSIC_PLAYING;
    current_music->times = loop;

    // Rebobinem l'stream de vorbis al principi. Cobreix tant play-per-primera-
    // vegada com replays/canvis de track que tornen a la mateixa pista.
    stb_vorbis_seek_start(current_music->vorbis);

    current_music->stream = SDL_CreateAudioStream(&current_music->spec, &JA_audioSpec);
    if (!current_music->stream) {
        std::cout << "Failed to create audio stream!" << '\n';
        current_music->state = JA_MUSIC_STOPPED;
        return;
    }
    SDL_SetAudioStreamGain(current_music->stream, JA_musicVolume);

    // Pre-cargem el buffer abans de bindejar per evitar un underrun inicial.
    JA_PumpMusic(current_music);

    if (!SDL_BindAudioStream(sdlAudioDevice, current_music->stream)) {
        std::cout << "[ERROR] SDL_BindAudioStream failed!" << '\n';
    }
}

inline const char* JA_GetMusicFilename(const JA_Music_t* music = nullptr) {
    if (!music) music = current_music;
    if (!music || music->filename.empty()) return nullptr;
    return music->filename.c_str();
}

inline void JA_PauseMusic() {
    if (!JA_musicEnabled) return;
    if (!current_music || current_music->state != JA_MUSIC_PLAYING) return;

    current_music->state = JA_MUSIC_PAUSED;
    SDL_UnbindAudioStream(current_music->stream);
}

inline void JA_ResumeMusic() {
    if (!JA_musicEnabled) return;
    if (!current_music || current_music->state != JA_MUSIC_PAUSED) return;

    current_music->state = JA_MUSIC_PLAYING;
    SDL_BindAudioStream(sdlAudioDevice, current_music->stream);
}

inline void JA_StopMusic() {
    // Limpiar outgoing crossfade si existe
    if (outgoing_music.stream) {
        SDL_DestroyAudioStream(outgoing_music.stream);
        outgoing_music.stream = nullptr;
        outgoing_music.fade.active = false;
    }
    incoming_fade.active = false;

    if (!current_music || current_music->state == JA_MUSIC_INVALID || current_music->state == JA_MUSIC_STOPPED) return;

    current_music->state = JA_MUSIC_STOPPED;
    if (current_music->stream) {
        SDL_DestroyAudioStream(current_music->stream);
        current_music->stream = nullptr;
    }
    // Deixem el handle de vorbis viu — es tanca en JA_DeleteMusic.
    // Rebobinem perquè un futur JA_PlayMusic comence des del principi.
    if (current_music->vorbis) {
        stb_vorbis_seek_start(current_music->vorbis);
    }
}

inline void JA_FadeOutMusic(const int milliseconds) {
    if (!JA_musicEnabled) return;
    if (!current_music || current_music->state != JA_MUSIC_PLAYING) return;

    // Destruir outgoing anterior si existe
    if (outgoing_music.stream) {
        SDL_DestroyAudioStream(outgoing_music.stream);
        outgoing_music.stream = nullptr;
    }

    // Pre-omplim l'stream amb `milliseconds` de so: un cop robat, ja no
    // tindrà accés al vorbis decoder i només podrà drenar el que tinga.
    JA_PreFillOutgoing(current_music, milliseconds);

    // Robar el stream del current_music al outgoing
    outgoing_music.stream = current_music->stream;
    outgoing_music.fade = {true, SDL_GetTicks(), milliseconds, JA_musicVolume};

    // Dejar current_music sin stream (ya lo tiene outgoing)
    current_music->stream = nullptr;
    current_music->state = JA_MUSIC_STOPPED;
    if (current_music->vorbis) stb_vorbis_seek_start(current_music->vorbis);
    incoming_fade.active = false;
}

inline void JA_CrossfadeMusic(JA_Music_t* music, const int crossfade_ms, const int loop) {
    if (!JA_musicEnabled || !music || !music->vorbis) return;

    // Destruir outgoing anterior si existe (crossfade durante crossfade)
    if (outgoing_music.stream) {
        SDL_DestroyAudioStream(outgoing_music.stream);
        outgoing_music.stream = nullptr;
        outgoing_music.fade.active = false;
    }

    // Robar el stream de la musica actual al outgoing para el fade-out.
    // Pre-omplim amb `crossfade_ms` de so perquè no es quede en silenci
    // abans d'acabar el fade (l'stream robat ja no pot alimentar-se).
    if (current_music && current_music->state == JA_MUSIC_PLAYING && current_music->stream) {
        JA_PreFillOutgoing(current_music, crossfade_ms);
        outgoing_music.stream = current_music->stream;
        outgoing_music.fade = {true, SDL_GetTicks(), crossfade_ms, JA_musicVolume};
        current_music->stream = nullptr;
        current_music->state = JA_MUSIC_STOPPED;
        if (current_music->vorbis) stb_vorbis_seek_start(current_music->vorbis);
    }

    // Iniciar la nueva pista con gain=0 (el fade-in la sube gradualmente)
    current_music = music;
    current_music->state = JA_MUSIC_PLAYING;
    current_music->times = loop;

    stb_vorbis_seek_start(current_music->vorbis);
    current_music->stream = SDL_CreateAudioStream(&current_music->spec, &JA_audioSpec);
    if (!current_music->stream) {
        std::cout << "Failed to create audio stream for crossfade!" << '\n';
        current_music->state = JA_MUSIC_STOPPED;
        return;
    }
    SDL_SetAudioStreamGain(current_music->stream, 0.0f);
    JA_PumpMusic(current_music);  // pre-carrega abans de bindejar
    SDL_BindAudioStream(sdlAudioDevice, current_music->stream);

    // Configurar fade-in
    incoming_fade = {true, SDL_GetTicks(), crossfade_ms, 0.0f};
}

inline JA_Music_state JA_GetMusicState() {
    if (!JA_musicEnabled) return JA_MUSIC_DISABLED;
    if (!current_music) return JA_MUSIC_INVALID;

    return current_music->state;
}

inline void JA_DeleteMusic(JA_Music_t* music) {
    if (!music) return;
    if (current_music == music) {
        JA_StopMusic();
        current_music = nullptr;
    }
    if (music->stream) SDL_DestroyAudioStream(music->stream);
    if (music->vorbis) stb_vorbis_close(music->vorbis);
    // ogg_data (std::vector) i filename (std::string) s'alliberen sols
    // al destructor de JA_Music_t.
    delete music;
}

inline float JA_SetMusicVolume(float volume) {
    JA_musicVolume = SDL_clamp(volume, 0.0f, 1.0f);
    if (current_music && current_music->stream) {
        SDL_SetAudioStreamGain(current_music->stream, JA_musicVolume);
    }
    return JA_musicVolume;
}

inline void JA_SetMusicPosition(float /*value*/) {
    // No implementat amb el backend de streaming.
}

inline float JA_GetMusicPosition() {
    return 0.0f;
}

inline void JA_EnableMusic(const bool value) {
    if (!value && current_music && (current_music->state == JA_MUSIC_PLAYING)) JA_StopMusic();
    JA_musicEnabled = value;
}

// --- Sound Functions ---

inline JA_Sound_t* JA_LoadSound(uint8_t* buffer, uint32_t size) {
    auto sound = std::make_unique<JA_Sound_t>();
    Uint8* raw = nullptr;
    if (!SDL_LoadWAV_IO(SDL_IOFromMem(buffer, size), 1, &sound->spec, &raw, &sound->length)) {
        std::cout << "Failed to load WAV from memory: " << SDL_GetError() << '\n';
        return nullptr;
    }
    sound->buffer.reset(raw);  // adopta el SDL_malloc'd buffer
    return sound.release();
}

inline JA_Sound_t* JA_LoadSound(const char* filename) {
    auto sound = std::make_unique<JA_Sound_t>();
    Uint8* raw = nullptr;
    if (!SDL_LoadWAV(filename, &sound->spec, &raw, &sound->length)) {
        std::cout << "Failed to load WAV file: " << SDL_GetError() << '\n';
        return nullptr;
    }
    sound->buffer.reset(raw);  // adopta el SDL_malloc'd buffer
    return sound.release();
}

inline int JA_PlaySound(JA_Sound_t* sound, const int loop = 0, const int group = 0) {
    if (!JA_soundEnabled || !sound) return -1;

    int channel = 0;
    while (channel < JA_MAX_SIMULTANEOUS_CHANNELS && channels[channel].state != JA_CHANNEL_FREE) { channel++; }
    if (channel == JA_MAX_SIMULTANEOUS_CHANNELS) {
        // No hay canal libre, reemplazamos el primero
        channel = 0;
    }

    return JA_PlaySoundOnChannel(sound, channel, loop, group);
}

inline int JA_PlaySoundOnChannel(JA_Sound_t* sound, const int channel, const int loop, const int group) {
    if (!JA_soundEnabled || !sound) return -1;
    if (channel < 0 || channel >= JA_MAX_SIMULTANEOUS_CHANNELS) return -1;

    JA_StopChannel(channel);

    channels[channel].sound = sound;
    channels[channel].times = loop;
    channels[channel].pos = 0;
    channels[channel].group = group;
    channels[channel].state = JA_CHANNEL_PLAYING;
    channels[channel].stream = SDL_CreateAudioStream(&channels[channel].sound->spec, &JA_audioSpec);

    if (!channels[channel].stream) {
        std::cout << "Failed to create audio stream for sound!" << '\n';
        channels[channel].state = JA_CHANNEL_FREE;
        return -1;
    }

    SDL_PutAudioStreamData(channels[channel].stream, channels[channel].sound->buffer.get(), channels[channel].sound->length);
    SDL_SetAudioStreamGain(channels[channel].stream, JA_soundVolume[group]);
    SDL_BindAudioStream(sdlAudioDevice, channels[channel].stream);

    return channel;
}

inline void JA_DeleteSound(JA_Sound_t* sound) {
    if (!sound) return;
    for (int i = 0; i < JA_MAX_SIMULTANEOUS_CHANNELS; i++) {
        if (channels[i].sound == sound) JA_StopChannel(i);
    }
    // buffer es destrueix automàticament via RAII (SDLFreeDeleter).
    delete sound;
}

inline void JA_PauseChannel(const int channel) {
    if (!JA_soundEnabled) return;

    if (channel == -1) {
        for (int i = 0; i < JA_MAX_SIMULTANEOUS_CHANNELS; i++)
            if (channels[i].state == JA_CHANNEL_PLAYING) {
                channels[i].state = JA_CHANNEL_PAUSED;
                SDL_UnbindAudioStream(channels[i].stream);
            }
    } else if (channel >= 0 && channel < JA_MAX_SIMULTANEOUS_CHANNELS) {
        if (channels[channel].state == JA_CHANNEL_PLAYING) {
            channels[channel].state = JA_CHANNEL_PAUSED;
            SDL_UnbindAudioStream(channels[channel].stream);
        }
    }
}

inline void JA_ResumeChannel(const int channel) {
    if (!JA_soundEnabled) return;

    if (channel == -1) {
        for (int i = 0; i < JA_MAX_SIMULTANEOUS_CHANNELS; i++)
            if (channels[i].state == JA_CHANNEL_PAUSED) {
                channels[i].state = JA_CHANNEL_PLAYING;
                SDL_BindAudioStream(sdlAudioDevice, channels[i].stream);
            }
    } else if (channel >= 0 && channel < JA_MAX_SIMULTANEOUS_CHANNELS) {
        if (channels[channel].state == JA_CHANNEL_PAUSED) {
            channels[channel].state = JA_CHANNEL_PLAYING;
            SDL_BindAudioStream(sdlAudioDevice, channels[channel].stream);
        }
    }
}

inline void JA_StopChannel(const int channel) {
    if (channel == -1) {
        for (int i = 0; i < JA_MAX_SIMULTANEOUS_CHANNELS; i++) {
            if (channels[i].state != JA_CHANNEL_FREE) {
                if (channels[i].stream) SDL_DestroyAudioStream(channels[i].stream);
                channels[i].stream = nullptr;
                channels[i].state = JA_CHANNEL_FREE;
                channels[i].pos = 0;
                channels[i].sound = nullptr;
            }
        }
    } else if (channel >= 0 && channel < JA_MAX_SIMULTANEOUS_CHANNELS) {
        if (channels[channel].state != JA_CHANNEL_FREE) {
            if (channels[channel].stream) SDL_DestroyAudioStream(channels[channel].stream);
            channels[channel].stream = nullptr;
            channels[channel].state = JA_CHANNEL_FREE;
            channels[channel].pos = 0;
            channels[channel].sound = nullptr;
        }
    }
}

inline JA_Channel_state JA_GetChannelState(const int channel) {
    if (!JA_soundEnabled) return JA_SOUND_DISABLED;
    if (channel < 0 || channel >= JA_MAX_SIMULTANEOUS_CHANNELS) return JA_CHANNEL_INVALID;

    return channels[channel].state;
}

inline float JA_SetSoundVolume(float volume, const int group = -1) {
    const float v = SDL_clamp(volume, 0.0f, 1.0f);

    if (group == -1) {
        for (int i = 0; i < JA_MAX_GROUPS; ++i) {
            JA_soundVolume[i] = v;
        }
    } else if (group >= 0 && group < JA_MAX_GROUPS) {
        JA_soundVolume[group] = v;
    } else {
        return v;
    }

    // Aplicar volum als canals actius.
    for (int i = 0; i < JA_MAX_SIMULTANEOUS_CHANNELS; i++) {
        if ((channels[i].state == JA_CHANNEL_PLAYING) || (channels[i].state == JA_CHANNEL_PAUSED)) {
            if (group == -1 || channels[i].group == group) {
                if (channels[i].stream) {
                    SDL_SetAudioStreamGain(channels[i].stream, JA_soundVolume[channels[i].group]);
                }
            }
        }
    }
    return v;
}

inline void JA_EnableSound(const bool value) {
    if (!value) {
        JA_StopChannel(-1);
    }
    JA_soundEnabled = value;
}

inline float JA_SetVolume(float volume) {
    float v = JA_SetMusicVolume(volume);
    JA_SetSoundVolume(v, -1);
    return v;
}
